VERSION = v3.1.0

default: build

build:
	go build -mod=vendor -ldflags "-X sigs.k8s.io/kustomize/v3/pkg/commands/misc.kustomizeVersion=$(VERSION) -X sigs.k8s.io/kustomize/v3/pkg/commands/misc.gitCommit=95f3303493fdea243ae83b767978092396169baf -X sigs.k8s.io/kustomize/v3/pkg/commands/misc.buildDate=Wed Aug 7 09:36:54 UTC 2019"  -o kustomize cmd/kustomize/main.go

.PHONY: build default
